### ISSUE TITLE
Custom Deployment issues - NPM build errors 

### ISSUE THREAD

**Issue by nnm103** [Niek/obs-web#40]
Niek,

Wonderful web application, but I have a situation where I need to build and deploy this on internal servers.  On the internal servers is there a way to customize the interface (remove disconnect, force full screen), hardcode the IP address & port & password within the code itself? 

Also when building, I'm having the below issue.  Any help would be greatly appreciated.  Thank you. 

I have tried to use npm i and then run build on both windows and Mac and getting build errors.  Specifically on npm i, I get a warning regarding the repository field which I have ignored.  But when I run npm run build I get the following output:

fatal: not a git repository (or any of the parent directories): .git
[!] Error: Command failed: git rev-parse --short HEAD
fatal: not a git repository (or any of the parent directories): .git

Error: Command failed: git rev-parse --short HEAD
fatal: not a git repository (or any of the parent directories): .git

    at checkExecSyncError (child_process.js:611:11)
    at Object.execSync (child_process.js:647:15)
    at Object.<anonymous> (/Users/xxxx/Desktop/obs-web-master/rollup.config.js:27:49)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.require.extensions.<computed> [as .js] (/Users/xxxx/Desktop/obs-web-master/node_modules/rollup/dist/shared/loadConfigFile.js:513:20)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at loadConfigFromBundledFile (/Users/xxxx/Desktop/obs-web-master/node_modules/rollup/dist/shared/loadConfigFile.js:521:42)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! svelte-app@1.0.0 build: `rollup -c`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the svelte-app@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by Niek** [comment]
It seems you have downloaded the source without git. Can you please use git? The tarball is not supported (right now).
``git clone https://github.com/Niek/obs-web.git``

**Comment by nnm103** [comment]
Thank you.  Will do that.  Any advice on how to make the customization changes I indicated above?

**Comment by Niek** [comment]
Great! I'll close the issue for now. 

For customization, you need to change the code.
