### ISSUE TITLE
dose not compile or run on Debian 11

### ISSUE THREAD

**Issue by nanderer** [Niek/obs-web#404]
Hi,

i tried to get it to work using the instructions in your readme, but it dose not work:

```
 cd ..
t@ThinkPad:~/git$ git clone https://github.com/Niek/obs-web
Cloning into 'obs-web'...
remote: Enumerating objects: 2658, done.
remote: Counting objects: 100% (932/932), done.
remote: Compressing objects: 100% (295/295), done.
remote: Total 2658 (delta 870), reused 660 (delta 637), pack-reused 1726
Receiving objects: 100% (2658/2658), 2.43 MiB | 10.54 MiB/s, done.
Resolving deltas: 100% (1930/1930), done.
t@ThinkPad:~/git$ cd obs-web/
t@ThinkPad:~/git/obs-web$ s
;ss: command not found
t@ThinkPad:~/git/obs-web$ ls
Dockerfile  LICENSE  package.json  package-lock.json  public  README.md  rollup.config.js  src
t@ThinkPad:~/git/obs-web$ npm ci
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@rollup/plugin-commonjs@25.0.8',
npm WARN EBADENGINE   required: { node: '>=14.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@rollup/plugin-html@1.0.3',
npm WARN EBADENGINE   required: { node: '>=14.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@rollup/plugin-inject@5.0.5',
npm WARN EBADENGINE   required: { node: '>=14.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@rollup/plugin-node-resolve@15.2.3',
npm WARN EBADENGINE   required: { node: '>=14.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@rollup/plugin-terser@0.4.4',
npm WARN EBADENGINE   required: { node: '>=14.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@rollup/pluginutils@5.1.0',
npm WARN EBADENGINE   required: { node: '>=14.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'eslint-plugin-svelte@2.43.0',
npm WARN EBADENGINE   required: { node: '^14.17.0 || >=16.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'rollup@4.19.0',
npm WARN EBADENGINE   required: { node: '>=18.0.0', npm: '>=8.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'sass@1.77.8',
npm WARN EBADENGINE   required: { node: '>=14.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'svelte@4.2.18',
npm WARN EBADENGINE   required: { node: '>=16' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'type-fest@3.13.1',
npm WARN EBADENGINE   required: { node: '>=14.16' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm WARN deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
npm WARN deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
npm WARN deprecated @humanwhocodes/config-array@0.11.14: Use @eslint/config-array instead

added 470 packages, and audited 471 packages in 15s

141 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
t@ThinkPad:~/git/obs-web$ npm run buil
npm ERR! missing script: buil
npm ERR! 
npm ERR! Did you mean this?
npm ERR!     build

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/t/.npm/_logs/2024-08-05T01_09_16_347Z-debug.log
t@ThinkPad:~/git/obs-web$ npm run build

> svelte-app@1.0.0 build
> rollup -c --bundleConfigAsCjs

/home/t/git/obs-web/node_modules/rollup/dist/bin/rollup:1339
		valueString = valueString ?? String(value);
		                           ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code 1
npm ERR! path /home/t/git/obs-web
npm ERR! command failed
npm ERR! command sh -c rollup -c --bundleConfigAsCjs

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/t/.npm/_logs/2024-08-05T01_09_18_167Z-debug.log
t@ThinkPad:~/git/obs-web$ npm run build

> svelte-app@1.0.0 build
> rollup -c --bundleConfigAsCjs

/home/t/git/obs-web/node_modules/rollup/dist/bin/rollup:1339
		valueString = valueString ?? String(value);
		                           ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code 1
npm ERR! path /home/t/git/obs-web
npm ERR! command failed
npm ERR! command sh -c rollup -c --bundleConfigAsCjs

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/t/.npm/_logs/2024-08-05T01_09_31_964Z-debug.log
t@ThinkPad:~/git/obs-web$ npm ci
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@rollup/plugin-commonjs@25.0.8',
npm WARN EBADENGINE   required: { node: '>=14.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@rollup/plugin-html@1.0.3',
npm WARN EBADENGINE   required: { node: '>=14.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@rollup/plugin-inject@5.0.5',
npm WARN EBADENGINE   required: { node: '>=14.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@rollup/plugin-node-resolve@15.2.3',
npm WARN EBADENGINE   required: { node: '>=14.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@rollup/plugin-terser@0.4.4',
npm WARN EBADENGINE   required: { node: '>=14.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@rollup/pluginutils@5.1.0',
npm WARN EBADENGINE   required: { node: '>=14.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'eslint-plugin-svelte@2.43.0',
npm WARN EBADENGINE   required: { node: '^14.17.0 || >=16.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'rollup@4.19.0',
npm WARN EBADENGINE   required: { node: '>=18.0.0', npm: '>=8.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'sass@1.77.8',
npm WARN EBADENGINE   required: { node: '>=14.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'svelte@4.2.18',
npm WARN EBADENGINE   required: { node: '>=16' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'type-fest@3.13.1',
npm WARN EBADENGINE   required: { node: '>=14.16' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated @humanwhocodes/config-array@0.11.14: Use @eslint/config-array instead
npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm WARN deprecated glob@8.1.0: Glob versions prior to v9 are no longer supported
npm WARN deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead

added 470 packages, and audited 471 packages in 5s

141 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
t@ThinkPad:~/git/obs-web$ npm run build

> svelte-app@1.0.0 build
> rollup -c --bundleConfigAsCjs

/home/t/git/obs-web/node_modules/rollup/dist/bin/rollup:1339
		valueString = valueString ?? String(value);
		                           ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code 1
npm ERR! path /home/t/git/obs-web
npm ERR! command failed
npm ERR! command sh -c rollup -c --bundleConfigAsCjs

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/t/.npm/_logs/2024-08-05T01_09_45_149Z-debug.log
t@ThinkPad:~/git/obs-web$ uname -a
Linux ThinkPad 5.10.0-31-amd64 #1 SMP Debian 5.10.221-1 (2024-07-14) x86_64 GNU/Linux
t@ThinkPad:~/git/obs-web$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
t@ThinkPad:~/git/obs-web$ t@ThinkPad:~/git/obs-web$ npm ci
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@rollup/plugin-commonjs@25.0.8',
npm WARN EBADENGINE   required: { node: '>=14.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@rollup/plugin-html@1.0.3',
npm WARN EBADENGINE   required: { node: '>=14.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@rollup/plugin-inject@5.0.5',
npm WARN EBADENGINE   required: { node: '>=14.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@rollup/plugin-node-resolve@15.2.3',
npm WARN EBADENGINE   required: { node: '>=14.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.22.12', npm: '7.5.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@rollup/plugin-terser@0.4.4',
npm WARN EBADENGINE   required: { node: '>=14.0.0' },
 @ThinkPad:~/git/obs-web$ m/_logs/2024-08-05T01_09_45_149Z-debug.loges/run_main.js:60:12)adr_compatibilitybrary is deprecated. See the compatibility table on MDN: https://d
bash: t@ThinkPad:~/git/obs-web$
```

thanks for any help on this in advance,

n'anderer

**Comment by nanderer** [comment]
oh wait maybe youll also need this:

```
$ cat /home/t/.npm/_logs/2024-08-05T01_09_18_167Z-debug.log
0 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
1 info using npm@7.5.2
2 info using node@v12.22.12
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/usr/share/nodejs/npm/npmrc Completed in 2ms
5 timing config:load:builtin Completed in 2ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/home/t/git/obs-web/.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/home/t/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 7ms
19 verbose npm-session 8198a2c4ec044b4c
20 timing npm:load Completed in 15ms
21 timing command:run-script Completed in 88ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (/usr/share/nodejs/@npmcli/promise-spawn/index.js:64:27)
22 verbose stack     at ChildProcess.emit (events.js:314:20)
22 verbose stack     at maybeClose (internal/child_process.js:1022:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
23 verbose pkgid svelte-app@1.0.0
24 verbose cwd /home/t/git/obs-web
25 verbose Linux 5.10.0-31-amd64
26 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
27 verbose node v12.22.12
28 verbose npm  v7.5.2
29 error code 1
30 error path /home/t/git/obs-web
31 error command failed
32 error command sh -c rollup -c --bundleConfigAsCjs
33 verbose exit 1
```

**Comment by Niek** [comment]
Node v12 is ancient (more than 5 years old), please update to Node 20 LTS.
