### ISSUE TITLE
npm run dev fail on MacOS High Sierra 10.13.6

### ISSUE THREAD

**Issue by sperok** [Niek/obs-web#51]
obs-web runs nicely on my chromebooks but just tried a clean build on an older Mac that failed the npm run build and/or npm run dev steps with rollup throwing an error:

```
> rollup -c

/Users/sperok/mvp/obs-web/node_modules/rollup/dist/shared/loadConfigFile.js:494
        ? (await import(url.pathToFileURL(fileName).href)).default
                 ^^^^^^

SyntaxError: Unexpected token import

```
Steps to reproduce:

- git clone https://github.com/Niek/obs-web.git
- cd obs-web
- npm i
- npm run build

console log:

```
Speros-iMac:mvp sperok$ git clone https://github.com/Niek/obs-web.git
Cloning into 'obs-web'...
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 624 (delta 5), reused 8 (delta 2), pack-reused 607
Receiving objects: 100% (624/624), 1.25 MiB | 3.93 MiB/s, done.
Resolving deltas: 100% (320/320), done.
Speros-iMac:mvp sperok$ cd obs-web
Speros-iMac:obs-web sperok$ npm i
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN ws@7.4.4 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN ws@7.4.4 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN svelte-app@1.0.0 No repository field.
npm WARN svelte-app@1.0.0 No license field.

added 583 packages from 236 contributors in 13.885s
[+] no known vulnerabilities found [583 packages audited]

Speros-iMac:obs-web sperok$ npm run build

> svelte-app@1.0.0 build /Users/sperok/mvp/obs-web
> rollup -c

/Users/sperok/mvp/obs-web/node_modules/rollup/dist/shared/loadConfigFile.js:494
        ? (await import(url.pathToFileURL(fileName).href)).default
                 ^^^^^^

SyntaxError: Unexpected token import
    at new Script (vm.js:51:7)
    at createScript (vm.js:138:10)
    at Object.runInThisContext (vm.js:199:10)
    at Module._compile (module.js:624:28)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! svelte-app@1.0.0 build: `rollup -c`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the svelte-app@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sperok/.npm/_logs/2021-03-29T18_33_30_253Z-debug.log
Speros-iMac:obs-web sperok$ 
```

**Comment by Niek** [comment]
I seems you are running an older Node version, please update to Node 15.x and try again.

**Comment by sperok** [comment]
Thank you for the very prompt response. Issue resolved.
