### ISSUE TITLE
Included Dockerfile errors during build

### ISSUE THREAD

**Issue by teh-random-name** [Niek/obs-web#85]
Building the container from master with the provided Dockerfile, the process errors during the `rollup -c` step.
Complains about not having git in the path, of course adding `RUN apk --no-cache add git` to the Dockerfile solves the issue but I wanted to open an issue regarding it anyways.

If need be I can do a PR to fix it, though it would only really be a single change.

Log below.

```
tsmith@streambox:~/obs-web$ docker build -t obs-web:dev .
Sending build context to Docker daemon  1.711MB
Step 1/6 : FROM node:16-alpine
 ---> 5521a6fdce5c
Step 2/6 : COPY ./ ./
 ---> 84a33050b24a
Step 3/6 : RUN npm i && npm run build
 ---> Running in a0224fae4fa6
npm WARN deprecated rollup-plugin-inject@3.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-inject.

added 210 packages, and audited 211 packages in 14s

26 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
npm notice
npm notice New minor version of npm available! 8.5.0 -> 8.6.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.6.0>
npm notice Run `npm install -g npm@8.6.0` to update!
npm notice

> svelte-app@1.0.0 build
> rollup -c

/bin/sh: git: not found
[!] Error: Command failed: git rev-parse --short HEAD
/bin/sh: git: not found

Error: Command failed: git rev-parse --short HEAD
/bin/sh: git: not found

    at checkExecSyncError (node:child_process:828:11)
    at Object.execSync (node:child_process:902:15)
    at Object.<anonymous> (/rollup.config.js:27:84)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.require.extensions.<computed> [as .js] (/node_modules/rollup/dist/shared/loadConfigFile.js:614:20)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at loadConfigFromBundledFile (/node_modules/rollup/dist/shared/loadConfigFile.js:622:42)

The command '/bin/sh -c npm i && npm run build' returned a non-zero code: 1
```

**Comment by Niek** [comment]
Weird, I guess `git` was removed very recently from the Alpine images? Since the last Docker build yesterday [worked fine](https://github.com/Niek/obs-web/runs/5815472598?check_suite_focus=true).

Anyway, fixed now!

**Comment by Niek** [comment]
@all-contributors add @teh-random-name for bug
